### PR TITLE
PST-406 update readme and remove provisioning

### PR DESCRIPTION
**Pull request by pivnicek**
no logic changes here, just cleanup 

- update readme and remove provisioning

### CODE REVIEW

**Review by odinuv — APPROVED** [review]
lgtm
have you deleted the CI resources? or shall i?

**Comment by pivnicek** [comment]
do we need to do that right now?  what if we want to make a change to the old 3.x version?

**Comment by odinuv** [comment]
fair enough, create an issue then

**Comment by pivnicek** [comment]
https://keboola.atlassian.net/browse/PST-624

**Pull request merged**
